apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gloo-mesh-enterprise-license
  namespace: {{ .Release.Namespace }}
data:
  key: {{ required "A Gloo Mesh Enterprise license key is required" .Values.license | b64enc }}
