name: pull_request

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  e2e:
    name: end-to-end
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        istioctl-binary: [
            'https://github.com/istio/istio/releases/download/1.8.0-alpha.2/istio-1.8.0-alpha.2-linux-amd64.tar.gz'
        ]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Setup Private Repo Permissions
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global url."https://${TOKEN}@github.com/solo-io/".insteadOf "https://github.com/solo-io/"
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: "true"
          version: v0.8.0
      - name: Install Protoc
        uses: arduino/setup-protoc@master
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Clean
        run: make clean || true
      - name: e2e Tests
        env:
          RUN_KUBE_E2E: "1"
          ISTIOCTL_BINARY: ${{ matrix.istioctl-binary }}
          LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
        run: |
          go install github.com/onsi/ginkgo/ginkgo

          # install istioctl
          ISTIO_VERSION=istio-$(echo $ISTIOCTL_BINARY | grep -o "download/.*/" | sed 's/\bdownload\b//g' |  sed 's/[\/]//g')
          curl -sSL $ISTIOCTL_BINARY | tar -xzf - $ISTIO_VERSION/bin/istioctl
          # move istio binary to _output, which is gitignored, to avoid `-dirty` suffix when computing version in subsequent makefile invocations
          mkdir _output && mv $ISTIO_VERSION _output/$ISTIO_VERSION
          export PATH=$PWD/_output/$ISTIO_VERSION/bin:/opt/hostedtoolcache/kubectl/1.18.0/x64:$PATH
          istioctl version

          # meshctl install
          GLOO_MESH_VERSION=$(go list -f '{{ .Module.Version }}' github.com/solo-io/gloo-mesh/test/e2e/istio/pkg/tests) curl -sL https://run.solo.io/meshctl/install | sh
          export PATH=$HOME/.gloo-mesh/bin:$PATH

          make run-tests GINKGOFLAGS=-v
