name: release

on:
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
        name: Gcloud Login
      - name: Publish Helm
        run: |
          make publish-helm
